#!/usr/local/bin/dash
# prints battery level
echo $(
	upower -i $(upower -e | grep dev.battery.1) | grep percentage | awk '{print $2}' | sed 's/[^0-9]//g'
	upower -i $(upower -e | grep dev.battery.0) | grep percentage | awk '{print $2}' | sed 's/[^0-9]//g'
)
